#!/usr/bin/env python
# -*- coding: utf-8 -*-

##
# @package gui
# Definition of base window

from PyQt5.QtWidgets import QWidget, QPushButton, QGridLayout, QSpacerItem, QLineEdit
from PyQt5.QtCore import Qt, pyqtSlot
from ivsmath.parser import infixToPrefix
from collections import deque
from ivsmath.mathlib import MathLib

##
# @brief      Parses prefix notated expression into mathlib
# @param      x deque generated by infixToPrefix
# @return     MathLib compatible string
def calculate(x):
    token = x.popleft()
    if token == "+":
        return f"MathLib.add({calculate(x)}, {calculate(x)})"
    elif token == "-":
        return f"MathLib.sub({calculate(x)}, {calculate(x)})"
    elif token == "*":
        return f"MathLib.mul({calculate(x)}, {calculate(x)})"
    elif token == "/":
        return f"MathLib.div({calculate(x)}, {calculate(x)})"
    elif token == "!":
        return f"MathLib.factorial({calculate(x)}, {calculate(x)})"
    elif token == "^":
        return f"MathLib.power({calculate(x)}, {calculate(x)})"
    elif token == "_":
        return f"MathLib.root({calculate(x)}, {calculate(x)})"
    elif token == "%":
        return f"MathLib.mod({calculate(x)}, {calculate(x)})"
    else:
        return f"{token}"


##
# @brief      Processes button clicking
# @param      id id of clicked button
# @param      text text of clicked button
def click_process(id, text):
    if id in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9):
        IvsWidget.textBox.value += text
        if not len(IvsWidget.buffer):
            IvsWidget.buffer = [""]
        if IvsWidget.buffer[-1] not in (
            "-",
            "+",
            "*",
            "/",
            "%",
            "^",
            "!0",
            "_",
            "(",
            ")",
        ):
            IvsWidget.buffer[-1] += text
        else:
            IvsWidget.buffer.append(text)
    elif id in (13, 14, 22, 23):
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append(text)
    elif id == 15:
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append("*")
    elif id == 16:
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append("/")
    elif id == 17:
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append("_")
    elif id == 18:
        IvsWidget.textBox.value += "^"
        IvsWidget.buffer.append("^")
    elif id == 19:
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append("%")
    elif id == 20:
        IvsWidget.textBox.value += text
        IvsWidget.buffer.append("!")
        IvsWidget.buffer.append("0")
    elif id == 10:
        IvsWidget.textBox.value += text
        IvsWidget.buffer[-1] += "."
    elif id == 11:
        IvsWidget.textBox.value = ""
        IvsWidget.buffer = [""]
    elif id == 12:
        IvsWidget.textBox.backspace()
        if len(IvsWidget.buffer):
            if IvsWidget.buffer[-1] not in ("-", "+", "*", "/", "%", "^", "!0", "_"):
                IvsWidget.buffer[-1] = IvsWidget.buffer[-1][:-1]
                if not len(IvsWidget.buffer[-1]):
                    IvsWidget.buffer.pop()
            else:
                IvsWidget.buffer.pop()
    elif id == 21:
        try:
            sum = eval(calculate(deque(infixToPrefix(IvsWidget.buffer))))
            print(sum)
            IvsWidget.textBox.value = str(sum)
            IvsWidget.buffer = [str(sum)]
        except Exception as e:
            IvsWidget.buffer = ["0"]
            IvsWidget.textBox.value = "Syntax Error"


##
# @brief      Button base class
class IvsButton(QPushButton):
    ##
    # @brief      Constructor
    # @param      text text shown on the button
    # @param      id id of the button
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(args[0], **kwargs)
        self.__text = args[0]
        self.__id = args[1]
        self.clicked.connect(self.on_click)

    ##
    # @brief      Listener for button click
    @pyqtSlot()
    def on_click(self, *args, **kwargs):
        click_process(self.__id, self.__text)


##
# @brief     Class for "normal" buttons
class IvsPushButton(IvsButton):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)


##
# @brief      Class for "long" buttons
class IvsLongButton(IvsButton):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)


##
# @brief      Class for showing text
class IvsTextBox(QLineEdit):

    ##
    # @brief      Shown text getter
    # @return     Shown text
    @property
    def value(self):
        return self.text()

    ##
    # @brief      Shown text setter
    # @param      value text to be shown
    @value.setter
    def value(self, value):
        self.setText(value)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.setReadOnly(True)
        self.setAlignment(Qt.AlignRight)
        self.setPlaceholderText("0")


##
# @brief      Class describing layout
class IvsWidget(QWidget):

    textBox = None
    buffer = [""]

    def __init__(self) -> None:
        super().__init__()
        self.__textBox = IvsTextBox()
        IvsWidget.textBox = self.__textBox
        self.setFocusPolicy(Qt.StrongFocus)
        self.__layout = QGridLayout()
        self.__layout.addWidget(self.__textBox, 0, 0, 1, 3)
        self.__layout.addWidget(IvsLongButton("0", 0), 4, 0, 1, 2)
        self.__layout.addWidget(IvsPushButton("1", 1), 3, 0)
        self.__layout.addWidget(IvsPushButton("2", 2), 3, 1)
        self.__layout.addWidget(IvsPushButton("3", 3), 3, 2)
        self.__layout.addWidget(IvsPushButton("4", 4), 2, 0)
        self.__layout.addWidget(IvsPushButton("5", 5), 2, 1)
        self.__layout.addWidget(IvsPushButton("6", 6), 2, 2)
        self.__layout.addWidget(IvsPushButton("7", 7), 1, 0)
        self.__layout.addWidget(IvsPushButton("8", 8), 1, 1)
        self.__layout.addWidget(IvsPushButton("9", 9), 1, 2)
        self.__layout.addWidget(IvsPushButton(".", 10), 4, 2)
        self.__layout.addItem(QSpacerItem(50, 100), 0, 3)
        self.__layout.addWidget(IvsPushButton("AC", 11), 0, 4)
        self.__layout.addWidget(IvsPushButton("C", 12), 0, 5)
        self.__layout.addWidget(IvsPushButton("+", 13), 1, 4)
        self.__layout.addWidget(IvsPushButton("-", 14), 1, 5)
        self.__layout.addWidget(IvsPushButton("(", 22), 5, 1)
        self.__layout.addWidget(IvsPushButton(")", 23), 5, 2)
        self.__layout.addWidget(IvsPushButton("×", 15), 2, 5)
        self.__layout.addWidget(IvsPushButton("÷", 16), 3, 5)
        self.__layout.addWidget(IvsPushButton("√", 17), 2, 4)
        self.__layout.addWidget(IvsPushButton("xⁿ", 18), 3, 4)
        self.__layout.addWidget(IvsPushButton("mod", 19), 4, 4)
        self.__layout.addWidget(IvsPushButton("!", 20), 5, 4)
        self.__layout.addWidget(IvsLongButton("=", 21), 4, 5, 2, 1)
        self.__layout.setHorizontalSpacing(0)
        self.__layout.setVerticalSpacing(0)
        self.setLayout(self.__layout)
